### ISSUE TITLE
[BUG] Forge clients can't join at all with default value of forge.blacklistedmods.list

### ISSUE THREAD

**Issue by aft2d** [magmafoundation/Magma#70]
**Describe the bug**
The default value of forge.blacklistedmods.list is an empty string:
```yaml
forge:
  blacklistedmods:
    list: ''
    kickmessage: Please Remove Blacklisted Mods
```

As soon as a client with forge installed tries to connect he's not able to join and get kicked with "Please Remove Blacklisted Mods".
(Even if the client does not have a mod installed at all.)
A vanilla client is able to join.

**To Reproduce**
1. Install a plain new magma server (v1f2f94f)
2. Install forge on your client and start it
3. Try to join -> kicked: "Please Remove Blacklisted Mods"

**Expected behavior**
Player is able to join

**Screenshots**
![image](https://user-images.githubusercontent.com/6129115/74235399-2d4a3280-4ccf-11ea-9f97-a349400518b9.png)
![image](https://user-images.githubusercontent.com/6129115/74234998-66ce6e00-4cce-11ea-9b59-133666b9a0f8.png)
![image](https://user-images.githubusercontent.com/6129115/74235016-6d5ce580-4cce-11ea-9f64-09d774ac7403.png)
![image](https://user-images.githubusercontent.com/6129115/74235028-75b52080-4cce-11ea-9ecb-9a14aca697f6.png)

**Info (please complete the following information):**
- Mod Name: no mod installed
 - Mod Version: no mod installed
 - Magma Version: 1.12.2 v1f2f94f
 - OS: Server: Ubuntu bionic / Client: elementary OS 0.4.1 (Ubuntu xenial)

**Additional context**
A small workaround is to set the forge.blacklistedmods.list value to a yaml list with one empty entry
```yaml
forge:
  blacklistedmods:
    list:
      - 
    kickmessage: Please Remove Blacklisted Mods
```

Let me know if I am right with my assumption and if you need more information.

Thanks in advance
~ Roman from Aternos
